-- Add all the missing projects to complete the portfolio

INSERT INTO projects (
  title, 
  description, 
  long_description,
  category, 
  technologies, 
  status, 
  featured, 
  github_url, 
  demo_url, 
  start_date, 
  end_date,
  impact,
  sort_order
) VALUES 
(
  'AI Learning Management System',
  'Intelligent LMS with personalized learning paths and AI-powered content recommendations for students.',
  'Developed a comprehensive Learning Management System that leverages artificial intelligence to create personalized learning experiences. The system analyzes student performance patterns and provides customized content recommendations, adaptive assessments, and intelligent tutoring capabilities. Features include real-time progress tracking, collaborative learning tools, and automated grading systems.',
  'web',
  ARRAY['React', 'Node.js', 'Python', 'TensorFlow', 'MongoDB', 'Express.js', 'TypeScript', 'Machine Learning'],
  'completed',
  true,
  'https://github.com/natnael-dejene/ai-lms',
  'https://ai-lms-demo.vercel.app',  
  '2023-08-01',
  '2024-01-15',
  'Improved student engagement by 40% and reduced course completion time by 25% through personalized learning paths',
  1
),
(
  'Linux System Monitor',
  'Real-time system monitoring dashboard for Linux servers with performance analytics and alerting.',
  'Built a comprehensive system monitoring solution for Linux environments featuring real-time CPU, memory, disk, and network monitoring. The dashboard provides detailed performance analytics, historical data trends, and configurable alerting mechanisms. Includes features for process management, service monitoring, and automated performance reporting.',
  'desktop',
  ARRAY['Python', 'Tkinter', 'SQLite', 'Linux', 'Bash', 'System Administration', 'C++'],
  'completed',
  true,
  'https://github.com/natnael-dejene/linux-monitor',
  null,
  '2023-03-01',
  '2023-06-30',
  'Deployed across 50+ servers, reduced system downtime by 30% through proactive monitoring and alerting',
  2
),
(
  'Smart Parking Management System',
  'IoT-enabled parking solution with real-time space detection and mobile app integration.',
  'Developed an intelligent parking management system that uses IoT sensors and computer vision to monitor parking space availability in real-time. The solution includes a mobile application for users to find and reserve parking spots, payment integration, and an admin dashboard for parking facility management. Features automated entry/exit management and revenue tracking.',
  'mobile',
  ARRAY['Flutter', 'Dart', 'Firebase', 'Python', 'OpenCV', 'Arduino', 'IoT', 'REST API'],
  'completed',
  true,
  'https://github.com/natnael-dejene/smart-parking',
  'https://smart-parking-demo.web.app',
  '2023-10-01',
  '2024-03-15',
  'Increased parking efficiency by 60% and reduced search time from 10 minutes to 2 minutes on average',
  3
),
(
  'Hotel Management System',
  'Comprehensive hotel operations platform with booking, inventory, and customer management.',
  'Created a full-featured hotel management system that streamlines hotel operations including room booking, inventory management, customer relationship management, and financial reporting. The system supports multiple user roles, integrates with payment gateways, and provides analytics for business insights. Features include automated billing, housekeeping management, and guest communication tools.',
  'web',
  ARRAY['Django', 'Python', 'PostgreSQL', 'HTML/CSS', 'JavaScript', 'Bootstrap', 'Payment Integration'],
  'completed',
  false,
  'https://github.com/natnael-dejene/hotel-management',
  null,
  '2022-09-01',
  '2023-01-20',
  'Reduced manual processing time by 70% and improved guest satisfaction scores by 35%',
  4
),
(
  'E-Commerce Platform',
  'Full-stack e-commerce solution with payment integration and inventory management.',
  'Built a scalable e-commerce platform featuring product catalog management, shopping cart functionality, secure payment processing, and order tracking. The platform includes an admin panel for inventory management, sales analytics, and customer management. Implemented responsive design, SEO optimization, and multi-vendor support capabilities.',
  'web',
  ARRAY['React', 'Node.js', 'MongoDB', 'Express.js', 'Stripe API', 'AWS S3', 'Redis', 'JWT'],
  'completed',
  false,
  'https://github.com/natnael-dejene/ecommerce-platform',
  'https://ecommerce-demo.netlify.app',
  '2023-05-01',
  '2023-09-30',
  'Processed 1000+ transactions with 99.9% uptime and achieved sub-2 second page load times',
  5
),
(
  'Portfolio Website',
  'Dynamic portfolio website showcasing projects and skills with modern design and animations.',
  'Designed and developed a professional portfolio website featuring dynamic content management, smooth animations, and responsive design. The site includes project showcases, skill demonstrations, contact forms, and blog capabilities. Built with modern web technologies and optimized for performance and SEO.',
  'web',
  ARRAY['React', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Supabase', 'Vite'],
  'completed',
  false,
  'https://github.com/natnael-dejene/portfolio',
  'https://natnael-dejene.com',
  '2024-08-01',
  '2024-09-06',
  'Increased professional visibility and received 50+ project inquiries within first month',
  6
)